#pragma config(Sensor, dgtl1,  powerButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  gearShift,      sensorTouch)
#pragma config(Sensor, dgtl9,  gearvarFlash,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, gearIndicator,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, powervarFlash,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, powerIndicator, sensorLEDtoVCC)
#pragma config(Motor,  port2,           mainMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           gearshiftMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//this program is meant to show the interaction between two buttons and the responces given in led outputs.
//Power Button Variables
int powerbuttonStatus = 0;
int powerbuttonDisable = 0;
int powerledtoggle = 0;
//Gear Shift button Variables
int gearshiftStatus = 0;
int gearshiftDisable = 0;
int gearledtoggle = 0;
//Power button enable
void powerbuttonClear()
{
if(SensorValue(powerButton) == 0)
{
powerbuttonDisable = 0;
}
}
//Gear shift enable
void gearshiftClear()
{
if(SensorValue(gearShift) == 0)
{
gearshiftDisable = 0;
}
}
//Power led toggle Variable clear
void powerledstat()
{
if(powerledtoggle > 1)
{
powerledtoggle = 0;
}
}
//Gear led toggle Variable clear
void gearledstat()
{
if(gearledtoggle > 1)
{
gearledtoggle = 0;
}
}
//Reset all LED's prior to program execution
void cleanLeds()
{
turnLEDOff(gearvarFlash);
turnLEDOff(gearIndicator);
turnLEDOff(powervarFlash);
turnLEDOff(powerIndicator);
}
//Activate the gear shift function
void gearshiftFunction()
{
if(SensorValue(gearShift) == 1 && gearshiftDisable == 0)
		{
		gearshiftStatus = 1;
		}
if(gearshiftStatus > 0)
		{
		turnLEDOn(gearvarFlash);
		wait1Msec(250);
		gearledtoggle = gearledtoggle + 1;
		gearledstat();
		gearshiftStatus = 0;
		gearshiftDisable = 1;
		}
	else
		{
		turnLEDOff(gearvarFlash);
		}
		gearshiftClear();

		if(gearledtoggle == 0)
		{
		turnLEDOff(gearIndicator);
		}
		else
		{
		turnLEDOn(gearIndicator);
		}
}

//Activate the power button function
void powerbuttonFunction()
{
if(SensorValue(powerButton) == 1 && powerbuttonDisable == 0)
		{
		powerbuttonStatus = 1;
		}
if(powerbuttonStatus > 0)
		{
		turnLEDOn(powervarFlash);
		wait1Msec(250);
		powerledtoggle = powerledtoggle + 1;
		powerledstat();
		powerbuttonStatus = 0;
		powerbuttonDisable = 1;
		}
	else
		{
		turnLEDOff(powervarFlash);
		}
		powerbuttonClear();

		if(powerledtoggle == 0)
		{
		turnLEDOff(powerIndicator);
		stopMotor(mainMotor);
		}
		else
		{
		turnLEDOn(powerIndicator);
		startMotor(mainMotor,25);
		}
}


task main()
{
cleanLeds();
powerledstat();
gearledstat();
while(true)
{
powerbuttonFunction();
gearshiftFunction();
}
}
