#pragma config(Sensor, dgtl1,  powerButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  gearShift,      sensorTouch)
#pragma config(Sensor, dgtl9,  gearvarFlash,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, gearIndicator,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, powervarFlash,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, powerIndicator, sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// THIS WORKS!
int powerbuttonStatus = 0;
int powerbuttonDisable = 0;
int powerledtoggle = 0;


void powerbuttonClear()
{
if(SensorValue(powerButton) == 0)
{
powerbuttonDisable = 0;
}
}

void powerledstat()
{
if(powerledtoggle > 1)
{
powerledtoggle = 0;
}
}

task main()
{
powerledstat();
while(true)
{
if(SensorValue(powerButton) == 1 && powerbuttonDisable == 0)
		{
		powerbuttonStatus = 1;
		}
if(powerbuttonStatus > 0)
		{
		turnLEDOn(powervarFlash);
		wait1Msec(250);
		powerledtoggle = powerledtoggle + 1;
		powerledstat();
		powerbuttonStatus = 0;
		powerbuttonDisable = 1;
		}
	else
		{
		turnLEDOff(powervarFlash);
		}
		powerbuttonClear();

		if(powerledtoggle == 0)
		{
		turnLEDOff(powerIndicator);
		}
		else
		{
		turnLEDOn(powerIndicator);
		}
}
}
